### ISSUE TITLE
Config for Active Steam Engine Capacity

### ISSUE THREAD

**Issue by Stef-00012** [NatiM6/lazy-engines#2]
Would it be possible to add a config to modify the capacity of a steam engine so for example instead of `16384` it returns `32768` or any other number based on the config, this without modifying the total output of the boiler itself.

It'd be useful if for example someone wants to use `9` steam engines instead of `18` on a level `18` boiler.

I know there's a config in the Create mod that does this, but that config also increases the total output of the boiler itself and not just the steam engines.

**Comment by NatiM6** [comment]
Hmmm...
That is a great config idea. I've always considered bigger engines as "boilers that I can attach more engines to", so most of the config changes things that influence that, but that also stopped me from trying to edit this value directly.

It is a bit tricky, since boiler doesn't actually support stress. The level of the boiler is directly tied to the amount of attached engines. That's why changing the engine stress capacity changes the boiler, as the boiler is _being informed_ how much su it produces from the engines, not the other way around.

I'll see what I can do.
Thanks for supporting my mod!

**Comment by NatiM6** [comment]
The feature is added, feel free to see if it works they way you intended it to!
